Repository IEEE-SB-GECBH/DSA-Hacktoberfest22, pull requests merged in 2022-10, with the labels that each got.

#1 Added Kruskal's MST Algorithm
  Kruskal_Algorithm.cpp
  contributors.md
Labels: documentation

#15 Let's code together
  contributors.md
  python/Divide n Conquer/LCS.py
  python/Divide n Conquer/LPS.py
  python/Divide n Conquer/fibonacci.py
  python/Divide n Conquer/house_robber.py
  python/Divide n Conquer/min_cost.py
  python/Divide n Conquer/no._of_ways_last.py
  python/Divide n Conquer/number_factor.py
  python/divide_n_conquer.md
Labels: hacktoberfest-accepted, hacktoberfest-2022

#6 New branch
  contributors.md
  python/binarysearch.py
  python/linkedlist.py
Labels: hacktoberfest-accepted, hacktoberfest-2022

#7 Made a flappy-bird game played by AI using NEAT
  python/flappy-bird-game/Flappy Bird.py
  python/flappy-bird-game/README.md
  python/flappy-bird-game/config-feedforward.txt
  python/flappy-bird-game/imgs/base.png
  python/flappy-bird-game/imgs/bg.png
  python/flappy-bird-game/imgs/bird1.png
  python/flappy-bird-game/imgs/bird2.png
  python/flappy-bird-game/imgs/bird3.png
  python/flappy-bird-game/imgs/pipe.png
  python/flappy-bird-game/sounds/die.mp3
  python/flappy-bird-game/sounds/hit.mp3
  python/flappy-bird-game/sounds/point.mp3
  python/flappy-bird-game/sounds/swoosh.mp3
  python/flappy-bird-game/sounds/wing.mp3
Labels: hacktoberfest-2022

#9 Implemented simple binary search
  python/binary-search.py
Labels: hacktoberfest-accepted, hacktoberfest-2022

#26 Floyd Warshall
  contributors.md
  cpp/2_flyod_warshall.c
Labels: hacktoberfest-2022

#3 longArithArray
  cpp/LongArithSubarray.cpp
Labels: hacktoberfest-2022

#14 Added code for searching algorithms in CPP
  contributors.md
  cpp/ExponentialSearch.cpp
  cpp/FibonacciSearch.cpp
  cpp/sequential_search.cpp
Labels: hacktoberfest-2022

#16 Lets Come Code and Encrypt
  CaeserCipher.py
  contributors.md
Labels: hacktoberfest-2022
